---
- name: Prepare
  hosts: instance
  gather_facts: false
  tasks:
    - name: Install role dependencies
      raw: pip install docker
      become: true
      changed_when: false
    - name: create docker.sock
      raw: touch /var/run/docker.sock
      become: true
      changed_when: false
    - name: move docker.sock from tmp
      raw: mount --move /tmp/docker.sock /var/run/docker.sock
      become: true
      changed_when: false
